const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-addressbook",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"收货地址",
                        "menuJump":"列表",
                        "tableName":"address"
                    }
                ],
                "menu":"收货地址"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-cart",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"购物车",
                        "menuJump":"列表",
                        "tableName":"cart"
                    }
                ],
                "menu":"购物车"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-message",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"客服聊天",
                        "menuJump":"列表",
                        "tableName":"chat"
                    }
                ],
                "menu":"客服聊天"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"景点",
                        "menuJump":"列表",
                        "tableName":"jingdian"
                    }
                ],
                "menu":"景点"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"景点收藏",
                        "menuJump":"列表",
                        "tableName":"jingdianCollection"
                    }
                ],
                "menu":"景点收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"景点评价",
                        "menuJump":"列表",
                        "tableName":"jingdianCommentback"
                    }
                ],
                "menu":"景点评价"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"景点预约",
                        "menuJump":"列表",
                        "tableName":"jingdianOrder"
                    }
                ],
                "menu":"景点预约"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-goods",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品",
                        "menuJump":"列表",
                        "tableName":"shangpin"
                    }
                ],
                "menu":"商品"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"商品收藏",
                        "menuJump":"列表",
                        "tableName":"shangpinCollection"
                    }
                ],
                "menu":"商品收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"商品评价",
                        "menuJump":"列表",
                        "tableName":"shangpinCommentback"
                    }
                ],
                "menu":"商品评价"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品订单",
                        "menuJump":"列表",
                        "tableName":"shangpinOrder"
                    }
                ],
                "menu":"商品订单"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"研学",
                        "menuJump":"列表",
                        "tableName":"yanxue"
                    }
                ],
                "menu":"研学"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"研学收藏",
                        "menuJump":"列表",
                        "tableName":"yanxueCollection"
                    }
                ],
                "menu":"研学收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"研学留言",
                        "menuJump":"列表",
                        "tableName":"yanxueLiuyan"
                    }
                ],
                "menu":"研学留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"研学报名",
                        "menuJump":"列表",
                        "tableName":"yanxueYuyue"
                    }
                ],
                "menu":"研学报名"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
